### ISSUE TITLE
make dark mode theme permanent

### ISSUE THREAD

**Issue by wandored** [wandored/cadashboard#72]
dark mode setting does not persist

**Comment by wandored** [comment]
first we need to figure out what sets the dark mode in the code.  Its somewhere in the css javascript.   second we need to add a column to the user database that tracks their preference of light or dark mode and set it.

**Comment by JKinsella04** [comment]
**Update:** The issue with the website not persisting the dark mode has been resolved.

I'm pleased to let you know that I've identified and fixed the problem that was causing the dark mode preference to reset on page refresh. The issue was related to the way the website was interacting with the `localStorage` feature. I've implemented a solution that ensures the dark mode setting is stored and maintained even after refreshing the page.

Now, when users enable dark mode, their preference will be saved to local storage, and the website will correctly apply the dark mode styling each time they return to the page. This enhancement improves the user experience and provides consistency across visits.

Thank you for bringing this issue to our attention, and I appreciate your patience as we worked to resolve it. Please feel free to explore the website and provide any feedback or let me know if you encounter any further issues.

Best regards,
John Kinsella

**Comment by wandored** [comment]
did you push the code?  make a PR?
